/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class example_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public short num;
    public double position[];
    public double orientation[];
 
    public example_t()
    {
        position = new double[18];
        orientation = new double[24];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe8176c8f456d469fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.example_t.class))
            return 0L;
 
        classes.add(exlcm.example_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeShort(this.num); 
 
        for (int a = 0; a < 18; a++) {
            outs.writeDouble(this.position[a]); 
        }
 
        for (int a = 0; a < 24; a++) {
            outs.writeDouble(this.orientation[a]); 
        }
 
    }
 
    public example_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public example_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.example_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.example_t o = new exlcm.example_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.num = ins.readShort();
 
        this.position = new double[(int) 18];
        for (int a = 0; a < 18; a++) {
            this.position[a] = ins.readDouble();
        }
 
        this.orientation = new double[(int) 24];
        for (int a = 0; a < 24; a++) {
            this.orientation[a] = ins.readDouble();
        }
 
    }
 
    public exlcm.example_t copy()
    {
        exlcm.example_t outobj = new exlcm.example_t();
        outobj.timestamp = this.timestamp;
 
        outobj.num = this.num;
 
        outobj.position = new double[(int) 18];
        System.arraycopy(this.position, 0, outobj.position, 0, 18); 
        outobj.orientation = new double[(int) 24];
        System.arraycopy(this.orientation, 0, outobj.orientation, 0, 24); 
        return outobj;
    }
 
}

